### ISSUE TITLE
Darwin only?  Really?  

### ISSUE THREAD

**Issue by fdouglis** [mvdwoord/PyGNS3#2]
I installed this on Ubuntu 18, and the first command I ran (based on the README) complained that the operating system isn't supported.  I looked at the code, and from what I could see, it defines a configuration for the key "Darwin" and says Linux/Windows is TODO.

It's fair to put this out there and say it's only available for Mac.  But for that not to be front and center in the README is beyond me ... am I missing something?

**Comment by fdouglis** [comment]
I'll add that by simply adding Linux as another system type with the same config location, I was able to get things to run.

So far the only mutable operation seems to be start /stop -- everything else is simply reading state.  Have you implemented the other functionality that can create nodes, links, and so on?

**Comment by mvdwoord** [comment]
Hi, yes as I was developing this, I was working on a mac and had no incentive to test anything else. As you mentioned, it was a simple fix so.. hurray!
I wrote this a long time ago and have not had time nor incentives to continue. Feel free to fork and build it out from here. Currently I do not have the time to merge any pull requests, if you would have made one ;)

**Comment by fdouglis** [comment]
OK, thanks.  Since that's the only change of note so far, I won't worry about pushing back to github, but I'll keep that in mind.  Appreciate the reply.
